name: therapisttrack-frontend

services:
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      FRONTEND_PORT : '${FRONTEND_PORT}'
      BACKEND_URI: '${BACKEND_URI}'
      VITE_BASE: '${VITE_BASE}'