name: therapisttrack-frontend

services:
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      FRONTEND_PORT : '${FRONTEND_PORT}'
      BACKEND_URI: '${BACKEND_URI}'
      VITE_BASE: '${VITE_BASE}'
      VITE_TEST_PORT: '${VITE_TEST_PORT}'
      VITE_OAUTH_DOMAIN: '${VITE_OAUTH_DOMAIN}'
      VITE_OAUTH_CLIENT_ID: '${VITE_OAUTH_CLIENT_ID}'
      VITE_OAUTH_REDIRECT_URI: '${VITE_OAUTH_REDIRECT_URI}'
      VITE_OAUTH_LOGOUT_URI: '${VITE_OAUTH_LOGOUT_URI}'
      VITE_FREE_NAVIGATION: '${VITE_FREE_NAVIGATION}'