#!/bin/bash

# Generate the .env file for building
cat <<EOF > ./.env
FRONTEND_PORT=${FRONTEND_PORT}
VITE_BACKEND_URI=${VITE_BACKEND_URI}
VITE_BASE=${VITE_BASE}
VITE_TEST_PORT=${VITE_TEST_PORT}

# OAUTH

VITE_OAUTH_DOMAIN=${VITE_OAUTH_DOMAIN}
VITE_OAUTH_CLIENT_ID=${VITE_OAUTH_CLIENT_ID}
VITE_OAUTH_REDIRECT_URI=${VITE_OAUTH_REDIRECT_URI}
VITE_OAUTH_LOGOUT_URI=${VITE_OAUTH_LOGOUT_URI}
VITE_FREE_NAVIGATION=${VITE_FREE_NAVIGATION}
EOF

# Execute the original command
exec "$@"
